package com.aiorchestration.orchestrator.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO representing the response returned after an AI task has been processed.
 * <p>
 * Contains the result and relevant metadata such as task type, language,
 * model used, and operation status.
 * <p>
 * <p>
 * Example JSON (MVP version):
 * <p>
 * {
 * "result": "The article discusses climate impacts...",
 * "taskType": "summarization",
 * "language": "en",
 * "modelUsed": "mock-llm",
 * "status": "success",
 * "errorMessage": null
 * }
 *
 * @author Nehir
 * @version 0.1-MVP
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TaskResponse {

    /**
     * The output generated by the LLM — summary, code, translation, etc.
     */
    private String result;

    /**
     * The type of task that was handled.
     */
    private String taskType;

    /**
     * The language of the input/output.
     */
    private String language;

    /**
     * Identifier of the AI model used during processing.
     */
    private String modelUsed;

    /**
     * The result status: "success" or "error".
     */
    private String status;

    /**
     * A message describing the error if the task failed.
     */
    private String errorMessage;
}